api-module: ygoapi

base:
  profiles:
    active: local
  application:
    name: ygoapi
  server:
    port: 9800
    enable: true

    gin:
      mode: release

  logger:
    level: info

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root

sqlite:
  host: ./files/OmegaDB.cdb

rushduel:
  jp: ./files/RushDuelJP.cdb
  cn: ./files/RushDuelCN.cdb
