api-module: ygoapi

base:
  profiles:
    active: local
  application:
    name: ygoapi
  server:
    port: 9800
    enable: true

    gin:
      mode: release

  logger:
    level: info

mysql:
  host: mysql
  # host: 10.211.55.12
  port: 3306
  # port: 30006
  user: root
  password: root

sqlite:
  host: ./files/OmegaDB.cdb